#!/bin/sh

# This is included mainly for reference, I don't think most people will need
# something like this, but I'm lazy

rock -clang -g \
    +-L/opt/local/lib \
    +-I/opt/local/include \
    +-framework +Cocoa \
    +-framework +OpenGL \
    +-lglew \
    $*
