#!/bin/sh

# glew and frameworks included here because accounting for these on Mac OS is
# the only source of joy in my life

rock -clang -g \
    +-framework +Cocoa \
    +-framework +OpenGL \
    -lglew \
    $*
